P8105 HW3
================
Jiayi Shen
10/06/2018

Problem 1
=========

``` r
# install.packages("devtools")
devtools::install_github("p8105/p8105.datasets")
```

    ## Skipping install of 'p8105.datasets' from a github remote, the SHA1 (21f5ad1c) has not changed since last install.
    ##   Use `force = TRUE` to force installation

``` r
#load BRFSS data
library(p8105.datasets)
data(brfss_smart2010, package = "p8105.datasets")
```

``` r
brfss_smart2010 = brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(topic == "Overall Health") %>% 
  filter(response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) %>% 
  mutate(response = as_factor(response, levels = c("Excellent", "Very good", "Good", "Fair", "Poor"), ordered = TRUE))
```

``` r
# In 2002, what states were observed at 7 locations?
brfss_smart2010 %>% 
  filter(year == "2002") %>% 
  distinct(locationabbr, locationdesc) %>% 
  count(locationabbr) %>% 
  filter(n == 7)
```

    ## # A tibble: 3 x 2
    ##   locationabbr     n
    ##   <chr>        <int>
    ## 1 CT               7
    ## 2 FL               7
    ## 3 NC               7

``` r
# CT, FL and NC were 7 distinct "locationdesc" variables.
```

-   In 2002, CT, FL and NC were observed at 7 locations.

``` r
# create a relevant dataframe for spaghetti plot
spaghetti_df = 
brfss_smart2010 %>% 
  group_by(locationabbr, year) %>% 
  summarize(n_obs = sum(sample_size))

# a line plot that shows the number of obs in each state from 2002 to 2010. 
ggplot(spaghetti_df, aes(x = year, y = n_obs, color = locationabbr))+
  geom_line()+
  labs(x = "Year", 
       y = "Num. of observations",
       title = "The number of observations in each state from 2002 to 2010")
```

<img src="p8105_hw3_js5354_files/figure-markdown_github/spaghetti plot-1.png" width="90%" /> This line plot demonstrates the number of observations each year in each state. The time frame ranges from 2002 to 2010. One line represents the trend in he number of observations in one state. Different states are colored differently.

``` r
#First filter brfss data accordingly, and then calculate the mean and sd.
brfss_smart2010 %>% 
  filter(year %in% c("2002", "2006", "2010")) %>% 
  filter(locationabbr == "NY", response == "Excellent") %>% 
  group_by(year) %>% 
  summarize(mean_NY = mean(data_value), 
            sd_NY = sd(data_value)) %>% 
  knitr::kable(digits = 1)
```

|  year|  mean\_NY|  sd\_NY|
|-----:|---------:|-------:|
|  2002|      24.0|     4.5|
|  2006|      22.5|     4.0|
|  2010|      22.7|     3.6|

From 2002 to 2006, the average proportion of excellent response in all locations across NY dropped from 24.0% to 22.5%. And from 2006 to 2010, this proportion stayed relatively flat, around 22.5%. The variance between each location across the NY state decreased from 2002 to 2006 and then to 2010.

``` r
brfss_state_avg = 
brfss_smart2010 %>% 
  group_by(year, locationabbr, response) %>% 
  summarize(avg_prop = mean(data_value))

ggplot(brfss_state_avg, aes(x = year, y = avg_prop, color = locationabbr))+
  geom_line()+
  labs(x = "Year",
       y = "average proportion of each response",
       title = "The state-level average proportion of each response from 2002 to 2010") +
  facet_grid(. ~ response)
```

    ## Warning: Removed 1 rows containing missing values (geom_path).

<img src="p8105_hw3_js5354_files/figure-markdown_github/state level average of each response-1.png" width="90%" />

*commenting*
In general, the average proportion of responding either "excellent" or "very good" or "good" is greater than those of responding "fair" or "poor".

Problem 2
=========

``` r
data(instacart, package = "p8105.datasets")
```

This `instacart` dataset contains 1384617 observations and 15 variables, storing information related to orders placed on the instacart app. The dataset not only includes numeric variables, such as order ID and user ID, but also character variables like descriptive product names and department names, and a logical variable `reordered` stating whether the order was placed first time or not.

Taking `order_id` =1 placed by `user_id` = 112108 as an example, this specific order was consist of 8 items with their `product_id`, `product_name` and the order in which each item was added to the cart (`add_to_cart_order`) stated. If `reordered` =1, it means that the particular item was not the first time that customer purchased. `order_number` refers to the sequence number of this order that the user placed. In this order, the user purchased four of everything. `order_dow` = 4 and `order_hour_of_day` =12 means this order was placed on a Thursday on 12pm. It had been 30 days (`days_since_prior_order` = 30) since this user placed his/her last order on instacart. Information related to the location of each product in the supermarket is specified in `aisle_id`, `aisle`, `department_id` and `department`.

``` r
# The number of distinct aisles
distinct(instacart, aisle)
```

    ## # A tibble: 134 x 1
    ##    aisle                        
    ##    <chr>                        
    ##  1 yogurt                       
    ##  2 other creams cheeses         
    ##  3 fresh vegetables             
    ##  4 canned meat seafood          
    ##  5 fresh fruits                 
    ##  6 packaged cheese              
    ##  7 specialty cheeses            
    ##  8 water seltzer sparkling water
    ##  9 cream                        
    ## 10 packaged vegetables fruits   
    ## # ... with 124 more rows

``` r
# Frequency of each aisle
instacart %>% 
  group_by(aisle) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n))
```

    ## # A tibble: 134 x 2
    ##    aisle                              n
    ##    <chr>                          <int>
    ##  1 fresh vegetables              150609
    ##  2 fresh fruits                  150473
    ##  3 packaged vegetables fruits     78493
    ##  4 yogurt                         55240
    ##  5 packaged cheese                41699
    ##  6 water seltzer sparkling water  36617
    ##  7 milk                           32644
    ##  8 chips pretzels                 31269
    ##  9 soy lactosefree                26240
    ## 10 bread                          23635
    ## # ... with 124 more rows

-   Fresh fruits and vegetables are the two aisles from which most items are ordered. The frequency of fresh fruits/vegetables appeared in this dataset almost double the frequency of the third most popular aisle, packaged vegetables fruits.

``` r
# create a relevant dataframe for further plotting
aisle_freq = 
instacart %>% 
  group_by(aisle) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n))

# create a function to plot aisles with item number within specific interval.
plot_aisle = function (lower_lim, upper_lim){

  ggplot(filter(aisle_freq, n >= lower_lim & n < upper_lim), aes(x = reorder(aisle, -n), y = n)) +
  geom_bar(stat = "identity")  +
  geom_text(aes(label = n), size =3, position = position_dodge(width = 0.9), vjust = -0.25) +
  scale_y_continuous(name = "Number of items ordered") +
  scale_x_discrete(name = "Asile" ) +
  coord_cartesian(ylim = c(lower_lim*0.95, upper_lim*1.05)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
}

aisle_p1 = plot_aisle (0, 1000)
aisle_p2 = plot_aisle (1000, 2000)
aisle_p3 = plot_aisle (2000, 6000)
aisle_p4 = plot_aisle (6000, 13000)
aisle_p5 = plot_aisle (13000, 151000)

aisle_p1  
```

<img src="p8105_hw3_js5354_files/figure-markdown_github/plotting n. of items in each aisle-1.png" width="90%" />

``` r
aisle_p2  
```

<img src="p8105_hw3_js5354_files/figure-markdown_github/plotting n. of items in each aisle-2.png" width="90%" />

``` r
aisle_p3  
```

<img src="p8105_hw3_js5354_files/figure-markdown_github/plotting n. of items in each aisle-3.png" width="90%" />

``` r
aisle_p4 
```

<img src="p8105_hw3_js5354_files/figure-markdown_github/plotting n. of items in each aisle-4.png" width="90%" />

``` r
aisle_p5 
```

<img src="p8105_hw3_js5354_files/figure-markdown_github/plotting n. of items in each aisle-5.png" width="90%" />
